# Site settings

url: "http://bigsmilesforthelittleones.com"
title: "{ Big Smiles for the Little Ones }"
description: "The aim of this website is to document the events related to Big Smiles for the Little Ones in Canlawe, Calape, Bohol"
keywords: "smiles, volunteer, bohol, earthquake, Canlawe, Calape, children, help"
favicon: "/img/favicon2.ico"
black-favicon: "/img/hand.png"
google-tracking-id: ""
disqus-shortname: "bigsmilesforthelittleones"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Timeline: 'timeline'
  Contact: 'contact'

background-img: "/img/intro-bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  - image: "/img/timeline/jollibee.jpg"
    date: "August 14, 2015"
    description: "<a href=\"http://bigsmilesforthelittleones.com/volunteer/2015/08/14/big-smiles-for-the-little-ones-4.html\" target=\"_blank\">Big Smiles for the Little Ones Wave 4</a> Our main sponsor for this event is Mr Shawn Chia of <a href=\"http://www.netsource.sg\" target=\"_blank\">Netsource Pte Ltd (Singapore)</a>"
  - image: "/img/timeline/nov2014.jpg"
    date: "November 28, 2014"
    description: "<a href=\"http://bigsmilesforthelittleones.com/volunteer/2014/11/28/big-smiles-for-the-little-ones-3.html\" target=\"_blank\">Big Smiles for the Little Ones Wave 3</a> Habagat bags and school supplies with the help of Shawn Chia, Tracey Chew and Marevic Tubang from <a href=\"http://www.netsource.sg\" target=\"_blank\">Netsource Pte Ltd (Singapore)</a>."
  - image: "/img/timeline/aug2014.jpg"
    date: "August 13 and 16 2014"
    description: "<a href=\"http://bigsmilesforthelittleones.com/volunteer/2014/08/13/big-smiles-for-the-little-ones-2.html\" target=\"_blank\">Big Smiles for the Little Ones Wave 2</a> Thanks to <a href=\"http://www.netsource.sg\" target=\"_blank\">Netsource Pte Ltd (Singapore)</a> through Mr. Shawn Chia for donating Tshirts for these Kids."
  - image: "/img/timeline/feb2014.jpg"
    date: "February 1, 2014"
    description: "<a href=\"http://bigsmilesforthelittleones.com/volunteer/2014/02/01/big-smiles-for-the-little-ones-1.html\" target=\"_blank\">Big Smiles for the Little Ones Wave 1</a> with Elementary Students, Preschool, Day Care and those aged 5 and below."
  - image: "/img/timeline/earthquake.jpg"
    date: "October 15, 2013"
    description: "Bohol was struck by a devastating 7.2 magnitude <a href=\"http://bigsmilesforthelittleones.com/volunteer/2014/02/01/big-smiles-for-the-little-ones-1.html\" target=\"_blank\">earthquake</a> that killed more than 200 people."

# First image of the Career timeline
career-img: "/img/timeline/canlawe.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "facebook"
    url: "https://www.facebook.com/mlastomen"
  - title: "instagram"
    url: "https://instagram.com/ishvari1985"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
